name: The-White-Heart
favicon: null
layout_spectrum: 0.01964265084825456
typography_spectrum: 0.8755206828936934
title: The White Heart
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3604871283750981
  lightness: 0.17880438058637083
  saturation: 0.35842047818005085
  rhythmicContrast: 0.3433263851329684
purpose: []
